# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: "cimg/node:18.1.0"
    
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run: |
          node --version
      - run:
          name: Front-End Install
          command: |
            yarn frontend:install
      - run:
          name: Back-End Install
          command: |
            yarn backend:install
      - run:
          name: Front-End Build
          command: |
            yarn frontend:build
      - run:
          name: Back-End Build
          command: |
            yarn backend:build
      - run:
          name: Deploy App
          command: |
            yarn frontend:deploy
      
      - run:
          name: Installing deployment dependencies
          command: |          
            sudo apt-get -y -qq update
            sudo apt-get install python3-pip python3-dev build-essential
            sudo pip install --upgrade setuptools
            sudo pip install awsebcli --upgrade          
      - run:
          name: Deploy Server
          command: |-
            aws s3 cp ./udagram-api/www/Archive.zip $full-stack-ner
            eb deploy udagrem-api-dev

#deployment:
     # production:
      #  branch: master
          
            
           
     
#workflows:
  #build-and-test:
    #jobs:
      #- build-and-test:
       # context: aws
        #filters:
          #branches:
            #only: 
              #- master



